### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by markflaisz** [vargalex/plugin.video.tv2play#2]
2024-09-01 12:04:14.836 T:1937355840   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2024-09-01 12:04:18.825 T:1636270976   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <c>
                                            Error Contents: 'ascii' codec can't encode character u'\xf3' in position 10: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.tv2play/default.py", line 600, in <module>
                                                musorok()
                                              File "/storage/.kodi/addons/plugin.video.tv2play/default.py", line 314, in musorok
                                                allItemsSorted=sorted(allItems, key=lambda k: locale.strxfrm(k["title"].lower()))
                                              File "/storage/.kodi/addons/plugin.video.tv2play/default.py", line 314, in <lambda>
                                                allItemsSorted=sorted(allItems, key=lambda k: locale.strxfrm(k["title"].lower()))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 10: ordinal not in range(128)
                                            -->End of Python script error report<--
2024-09-01 12:04:18.951 T:1532380032   ERROR: GetDirectory - Error getting plugin://plugin.video.tv2play/?action=musorok
2024-09-01 12:04:18.953 T:1937355840   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tv2play/?action=musorok) failed

**Comment by markflaisz** [comment]
Szia, a Kodi hibanaplóban az alábbi üzenet fogad. Rendszer: Raspberry Pi3B Libreelec 9.2.8 Kodi 18.9. Újabb rendszeren a hiba nem tapasztalható, de nekem sajnos python 2 verzió miatt fontos a régebbi rendszer. Köszi előre is a segítséged.

**Comment by vargalex** [comment]
Üdv

Milyen operációs rendszer, milyen verziójú Kodi? Természetesen a Műsorlista sorrend Népszerűség-re történő módosításával meg kell szűnjön a probléma.

**Comment by markflaisz** [comment]
Köszönöm! “Népszerűségre” való váltással valóban megszűnt a probléma!

**Comment by vargalex** [comment]
Az 1.0.18-as verzióban javítottam. Most már megy a sorbarendezés Leia alatt is, igaz nálam a végére kerülnek az ékezetes karakterek.

**Comment by markflaisz** [comment]
Köszönjük szépen!
